FROM openjdk:8u322-jre-slim

WORKDIR /work

ENV SPARK_VERSION 3.5.1

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        procps \
        curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -SL "https://dlcdn.apache.org/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop3.tgz" | tar -xzC /opt

RUN mv "/opt/spark-$SPARK_VERSION-bin-hadoop3" /opt/spark

WORKDIR /opt/spark
