// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package example.rpc;

public interface GetOrdersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GetOrdersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rpc.Order order = 1;</code>
   */
  java.util.List<example.rpc.Order> 
      getOrderList();
  /**
   * <code>repeated .rpc.Order order = 1;</code>
   */
  example.rpc.Order getOrder(int index);
  /**
   * <code>repeated .rpc.Order order = 1;</code>
   */
  int getOrderCount();
  /**
   * <code>repeated .rpc.Order order = 1;</code>
   */
  java.util.List<? extends example.rpc.OrderOrBuilder> 
      getOrderOrBuilderList();
  /**
   * <code>repeated .rpc.Order order = 1;</code>
   */
  example.rpc.OrderOrBuilder getOrderOrBuilder(
      int index);
}
