// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package example.rpc;

public interface ItemOrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.ItemOrder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 item_id = 1;</code>
   * @return The itemId.
   */
  int getItemId();

  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();
}
