// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package example.rpc;

public interface RepaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.RepaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 customer_id = 1;</code>
   * @return The customerId.
   */
  int getCustomerId();

  /**
   * <code>int32 amount = 2;</code>
   * @return The amount.
   */
  int getAmount();
}
