// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface GetCustomerInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GetCustomerInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 credit_limit = 3;</code>
   * @return The creditLimit.
   */
  int getCreditLimit();

  /**
   * <code>int32 credit_total = 4;</code>
   * @return The creditTotal.
   */
  int getCreditTotal();
}
