// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface GetCustomerInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GetCustomerInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 customer_id = 1;</code>
   * @return The customerId.
   */
  int getCustomerId();
}
