// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface GetOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GetOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();
}
