// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>int32 customer_id = 3;</code>
   * @return The customerId.
   */
  int getCustomerId();

  /**
   * <code>string customer_name = 4;</code>
   * @return The customerName.
   */
  java.lang.String getCustomerName();
  /**
   * <code>string customer_name = 4;</code>
   * @return The bytes for customerName.
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>repeated .rpc.Statement statement = 5;</code>
   */
  java.util.List<sample.rpc.Statement> 
      getStatementList();
  /**
   * <code>repeated .rpc.Statement statement = 5;</code>
   */
  sample.rpc.Statement getStatement(int index);
  /**
   * <code>repeated .rpc.Statement statement = 5;</code>
   */
  int getStatementCount();
  /**
   * <code>repeated .rpc.Statement statement = 5;</code>
   */
  java.util.List<? extends sample.rpc.StatementOrBuilder> 
      getStatementOrBuilderList();
  /**
   * <code>repeated .rpc.Statement statement = 5;</code>
   */
  sample.rpc.StatementOrBuilder getStatementOrBuilder(
      int index);

  /**
   * <code>int32 total = 6;</code>
   * @return The total.
   */
  int getTotal();
}
