// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface PaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.PaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transaction_id = 1;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 1;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>int32 customer_id = 2;</code>
   * @return The customerId.
   */
  int getCustomerId();

  /**
   * <code>int32 amount = 3;</code>
   * @return The amount.
   */
  int getAmount();
}
