// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface StatementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.Statement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 item_id = 1;</code>
   * @return The itemId.
   */
  int getItemId();

  /**
   * <code>string item_name = 2;</code>
   * @return The itemName.
   */
  java.lang.String getItemName();
  /**
   * <code>string item_name = 2;</code>
   * @return The bytes for itemName.
   */
  com.google.protobuf.ByteString
      getItemNameBytes();

  /**
   * <code>int32 price = 3;</code>
   * @return The price.
   */
  int getPrice();

  /**
   * <code>int32 count = 4;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>int32 total = 5;</code>
   * @return The total.
   */
  int getTotal();
}
