version: "3.9"
services:
  cassandra:
    image: cassandra:3.11
    container_name: "cassandradb-1"
    volumes:
      - cassandra-data:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - scalar-network

  schema-loader:
    image: ghcr.io/scalar-labs/scalardb-schema-loader:3.5.0
    container_name: "scalardb-schema-loader-1"
    volumes:
      - ./database.properties:/database.properties
      - ./emoney-schema.json:/emoney-schema.json
    command: "--config /database.properties -f /emoney-schema.json --coordinator"
    networks:
      - scalar-network
    profiles:
      - tools

  scalardb-graphql:
    image: ghcr.io/scalar-labs/scalardb-graphql:3.5.0
    container_name: "scalardb-graphql-1"
    depends_on:
      - cassandra
    restart: "always"
    volumes:
      - ./database.properties:/scalardb-graphql/database.properties
      - ./wait-for-it.sh:/scalardb-graphql/wait-for-it.sh
    ports:
      - "8080:8080" # scalardb-graphql-server port
    entrypoint: /bin/bash
    command: ./wait-for-it.sh -t 60 cassandra:9042 -- ./bin/scalardb-graphql-server --config database.properties
    networks:
      - scalar-network

networks:
  scalar-network:
    name: scalar-network

volumes:
  cassandra-data:
