// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface GetOrdersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GetOrdersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The customer ID of the customer.
   * </pre>
   *
   * <code>int32 customer_id = 1;</code>
   * @return The customerId.
   */
  int getCustomerId();
}
