// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface GetOrdersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GetOrdersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The order information.
   * </pre>
   *
   * <code>repeated .rpc.Order order = 1;</code>
   */
  java.util.List<sample.rpc.Order> 
      getOrderList();
  /**
   * <pre>
   * The order information.
   * </pre>
   *
   * <code>repeated .rpc.Order order = 1;</code>
   */
  sample.rpc.Order getOrder(int index);
  /**
   * <pre>
   * The order information.
   * </pre>
   *
   * <code>repeated .rpc.Order order = 1;</code>
   */
  int getOrderCount();
  /**
   * <pre>
   * The order information.
   * </pre>
   *
   * <code>repeated .rpc.Order order = 1;</code>
   */
  java.util.List<? extends sample.rpc.OrderOrBuilder> 
      getOrderOrBuilderList();
  /**
   * <pre>
   * The order information.
   * </pre>
   *
   * <code>repeated .rpc.Order order = 1;</code>
   */
  sample.rpc.OrderOrBuilder getOrderOrBuilder(
      int index);
}
