// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface PaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.PaymentResponse)
    com.google.protobuf.MessageOrBuilder {
}
