// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface RepaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.RepaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The customer ID of the customer.
   * </pre>
   *
   * <code>int32 customer_id = 1;</code>
   * @return The customerId.
   */
  int getCustomerId();

  /**
   * <pre>
   * The amount of the repayment.
   * </pre>
   *
   * <code>int32 amount = 2;</code>
   * @return The amount.
   */
  int getAmount();
}
