// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public final class Sample {
  private Sample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ItemOrder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ItemOrder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_PlaceOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_PlaceOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_PlaceOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_PlaceOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Order_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Statement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Statement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetOrdersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetOrdersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetOrdersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetOrdersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetCustomerInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetCustomerInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetCustomerInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetCustomerInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_PaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_PaymentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_RepaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_RepaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_RepaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_RepaymentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sample.proto\022\003rpc\"+\n\tItemOrder\022\017\n\007item" +
      "_id\030\001 \001(\005\022\r\n\005count\030\002 \001(\005\"L\n\021PlaceOrderRe" +
      "quest\022\023\n\013customer_id\030\001 \001(\005\022\"\n\nitem_order" +
      "\030\002 \003(\0132\016.rpc.ItemOrder\"&\n\022PlaceOrderResp" +
      "onse\022\020\n\010order_id\030\001 \001(\t\"\212\001\n\005Order\022\020\n\010orde" +
      "r_id\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\003\022\023\n\013custome" +
      "r_id\030\003 \001(\005\022\025\n\rcustomer_name\030\004 \001(\t\022!\n\tsta" +
      "tement\030\005 \003(\0132\016.rpc.Statement\022\r\n\005total\030\006 " +
      "\001(\005\"\\\n\tStatement\022\017\n\007item_id\030\001 \001(\005\022\021\n\tite" +
      "m_name\030\002 \001(\t\022\r\n\005price\030\003 \001(\005\022\r\n\005count\030\004 \001" +
      "(\005\022\r\n\005total\030\005 \001(\005\"#\n\017GetOrderRequest\022\020\n\010" +
      "order_id\030\001 \001(\t\"-\n\020GetOrderResponse\022\031\n\005or" +
      "der\030\001 \001(\0132\n.rpc.Order\"\'\n\020GetOrdersReques" +
      "t\022\023\n\013customer_id\030\001 \001(\005\".\n\021GetOrdersRespo" +
      "nse\022\031\n\005order\030\001 \003(\0132\n.rpc.Order\"]\n\026GetCus" +
      "tomerInfoRequest\022\033\n\016transaction_id\030\001 \001(\t" +
      "H\000\210\001\001\022\023\n\013customer_id\030\002 \001(\005B\021\n\017_transacti" +
      "on_id\"_\n\027GetCustomerInfoResponse\022\n\n\002id\030\001" +
      " \001(\005\022\014\n\004name\030\002 \001(\t\022\024\n\014credit_limit\030\003 \001(\005" +
      "\022\024\n\014credit_total\030\004 \001(\005\"M\n\016PaymentRequest" +
      "\022\026\n\016transaction_id\030\001 \001(\t\022\023\n\013customer_id\030" +
      "\002 \001(\005\022\016\n\006amount\030\003 \001(\005\"\021\n\017PaymentResponse" +
      "\"7\n\020RepaymentRequest\022\023\n\013customer_id\030\001 \001(" +
      "\005\022\016\n\006amount\030\002 \001(\005\"\023\n\021RepaymentResponse2\310" +
      "\001\n\014OrderService\022?\n\nPlaceOrder\022\026.rpc.Plac" +
      "eOrderRequest\032\027.rpc.PlaceOrderResponse\"\000" +
      "\0229\n\010GetOrder\022\024.rpc.GetOrderRequest\032\025.rpc" +
      ".GetOrderResponse\"\000\022<\n\tGetOrders\022\025.rpc.G" +
      "etOrdersRequest\032\026.rpc.GetOrdersResponse\"" +
      "\0002\327\001\n\017CustomerService\022N\n\017GetCustomerInfo" +
      "\022\033.rpc.GetCustomerInfoRequest\032\034.rpc.GetC" +
      "ustomerInfoResponse\"\000\0226\n\007Payment\022\023.rpc.P" +
      "aymentRequest\032\024.rpc.PaymentResponse\"\000\022<\n" +
      "\tRepayment\022\025.rpc.RepaymentRequest\032\026.rpc." +
      "RepaymentResponse\"\000B\026\n\nsample.rpcB\006Sampl" +
      "eP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rpc_ItemOrder_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_ItemOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ItemOrder_descriptor,
        new java.lang.String[] { "ItemId", "Count", });
    internal_static_rpc_PlaceOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_PlaceOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_PlaceOrderRequest_descriptor,
        new java.lang.String[] { "CustomerId", "ItemOrder", });
    internal_static_rpc_PlaceOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rpc_PlaceOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_PlaceOrderResponse_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_rpc_Order_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rpc_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Order_descriptor,
        new java.lang.String[] { "OrderId", "Timestamp", "CustomerId", "CustomerName", "Statement", "Total", });
    internal_static_rpc_Statement_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_rpc_Statement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Statement_descriptor,
        new java.lang.String[] { "ItemId", "ItemName", "Price", "Count", "Total", });
    internal_static_rpc_GetOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_rpc_GetOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetOrderRequest_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_rpc_GetOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_rpc_GetOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetOrderResponse_descriptor,
        new java.lang.String[] { "Order", });
    internal_static_rpc_GetOrdersRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_rpc_GetOrdersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetOrdersRequest_descriptor,
        new java.lang.String[] { "CustomerId", });
    internal_static_rpc_GetOrdersResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_rpc_GetOrdersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetOrdersResponse_descriptor,
        new java.lang.String[] { "Order", });
    internal_static_rpc_GetCustomerInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_rpc_GetCustomerInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetCustomerInfoRequest_descriptor,
        new java.lang.String[] { "TransactionId", "CustomerId", "TransactionId", });
    internal_static_rpc_GetCustomerInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_rpc_GetCustomerInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetCustomerInfoResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "CreditLimit", "CreditTotal", });
    internal_static_rpc_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_rpc_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_PaymentRequest_descriptor,
        new java.lang.String[] { "TransactionId", "CustomerId", "Amount", });
    internal_static_rpc_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_rpc_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_PaymentResponse_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_RepaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_rpc_RepaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_RepaymentRequest_descriptor,
        new java.lang.String[] { "CustomerId", "Amount", });
    internal_static_rpc_RepaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_rpc_RepaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_RepaymentResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
