version: "3.5"
services:
  mysql:
    image: mysql:8.1
    container_name: "mysql-1"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
  postgres:
    image: postgres:15
    container_name: "postgres-1"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  oracle:
    image: container-registry.oracle.com/database/free:23.4.0.0
    container_name: "oracle-1"
    environment:
      ORACLE_PWD: Oracle
    ports:
      - "1521:1521"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "sqlserver-1"
    environment:
      MSSQL_PID: "Express"
      SA_PASSWORD: "SqlServer22"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  dynamodb:
    image: amazon/dynamodb-local:2.5.2
    container_name: "dynamodb-1"
    ports:
      - "8000:8000"
  cassandra:
    image: cassandra:3.11
    container_name: "cassandra-1"
    ports:
      - "9042:9042"
