// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface GetCustomerInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GetCustomerInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string transaction_id = 1;</code>
   * @return Whether the transactionId field is set.
   */
  boolean hasTransactionId();
  /**
   * <code>optional string transaction_id = 1;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>optional string transaction_id = 1;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>int32 customer_id = 2;</code>
   * @return The customerId.
   */
  int getCustomerId();
}
