// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface PrepareRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.PrepareRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transaction_id = 1;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 1;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();
}
